name: GarminPhoto
options:
  bundleIdPrefix: com.gnoftheshark
  deploymentTarget:
    iOS: "15.0"

targets:
  App:
    type: application
    platform: iOS
    sources:
      - path: .
        excludes:
          - "project.yml"
          - ".github/**"
          - ".git/**"
    info:
      path: Info.plist
      properties:
        UILaunchStoryboardName: ""
        NSCameraUsageDescription: "Nécessaire pour afficher l'aperçu de la caméra"
        CFBundleDisplayName: "Garmin Photo"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.gnoftheshark.garminphoto
        SWIFT_VERSION: "5.0"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
